[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Gas settings for Filecoin deployment
gas_limit = 50000000
gas_price = 2000000000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
