[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Gas settings for Base deployment
gas_limit = 8000000
gas_price = 1000000000

# Base Network Configuration
[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
base_sepolia_ws = "wss://base-sepolia.drpc.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
